/** Target keywords (EN) for organic SEO — online courses and certificates. */
export const SEO_KEYWORDS_EN = [
  'online courses with fast certificate',
  'quick courses with certificate',
  'fast online certificate',
  'free online courses with certificate',
  'how to get a certificate quickly',
  'instant course certificate',
  'courses to boost your resume',
  'affordable online courses with certificate',
  'online course platform',
  'quick courses multiple subjects',
  'affordable recognized online courses',
  'cheap paid online certificate courses',
  'multiple courses fast certificate',
  'quick course platform',
  'accessible courses with certificate',
  'fast business administration courses',
  'technology courses with certificate',
  'fast online health courses',
  'education courses with certificate',
  'fast digital marketing courses',
  'beauty courses with certificate',
  'fast language courses',
  'issue certificate quickly',
  'cheap instant certificate',
  'fast vocational courses',
  'affordable professional qualification',
  'online course immediate certificate',
  'fast digital certificate',
  'courses for complementary hours',
  'fast certificate for college',
  'complementary hours college',
  '10 hour online course certificate',
  'fast distance learning courses',
  'free courses with certificate',
  'certificate valid nationwide Brazil',
  'quick courses for unemployed',
  'popular price online courses',
  '80 hour course certificate',
  '100 hour course certificate',
  '50 hour course certificate',
  '20 hour course certificate',
  'how to update resume quickly',
  'courses for exam points',
  'fast free course certificate',
  'affordable e-learning platform',
  'online courses on sale',
  'learn a profession quickly',
  'fast IT courses',
  'Excel online course certificate',
  'online administrative assistant course',
  'fast pedagogy courses',
  'sales and marketing courses',
  'instant digital certificates',
  'CONECT CURSOS',
  'Brazil online education',
  'e-learning',
] as const

export const SEO_KEYWORDS_EN_STRING = SEO_KEYWORDS_EN.join(', ')
